### ISSUE TITLE
Selector preview prevent me from clicking on “Accept Cookie” button

### ISSUE THREAD

**Issue by zydjohnHotmail** [checkly/headless-recorder#145] opened 2021-07-23 18:12 UTC
Hello:
I have used this tools for a few years now, it worked well.
However, today, I have to write some PuppeteerSharp code to visit one web page, for this web page, there is one button called “Accept” cookie at the middle- bottom part of the page, which you have to click on it, in order to go further.
For old version of this tools, it should be no issue at all.  But the current version 1.0.0 has something, I think it is called “Selector Preview”, which I can see the preview of the element the mouse hovers; but the biggest issue is: this “Selector Preview” just covers the “Accept” cookie button, and I can’t figure out how to move this “Selector Preview” to somewhere else, therefore, I can’t click on the “Accept” cookie button.
Please let me able to configure where to show the “Selector Preview” on the whole screen area, but not fix it in one specific area.  You can imagine that some specific button, like those “Accept Cookie” buttons will usually be placed at the bottom part of one page, and if I can’t move the “Selector Preview” to somewhere else, how I can click on the “Accept Cookie” button?
Hope you understand.

**Comment by ianaya89** [comment] 2021-07-23 18:29
Already working on a toggle feature to solve this.

Duplicate of #144

**Closed by ianaya89** 2021-07-23 18:29 UTC
